server:
    port: 8090
---
spring:
    config:
        activate:
            on-profile: dev
    datasource.hikari:
        # connection-test-query: SELECT 1;
        maximum-pool-size: 2
        minimum-idle: 1
        connection-timeout: 30000
        validation-timeout: 5000
        idle-timeout: 1800000
        max-lifetime: 3600000
        keepalive-time: 300000
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        # jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/soo_coolmove
        # username: soo
        # password: soo#123
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/soo
        username: soo
        password: soo#123
---
logging:
    # config: classpath:log4j2.xml
    level:
        root: info
        jdbc:
            sqlonly: info
            resultsettable: info
            sqltiming: off
            audit: off
            resultset: off
        log4jdbc.log4j2: warn
        connection: off
---
app:
    config:
        # be-api-json: /nas/soo/apps/soo-dev/be-java-maven/config/api.json
        # be-env-json: /nas/soo/apps/soo-dev/be-java-maven/config/env.json
        # fe-env-json: /nas/soo/apps/soo-dev/fe-vite-react-ts/config/env.json
        be-api-json: /develop/com.soo/soo-dev/apps/be-java-maven/config/api.json
        be-env-json: /develop/com.soo/soo-dev/apps/be-java-maven/config/env.json
        fe-env-json: /develop/com.soo/soo-dev/apps/fe-vite-react-ts/public/config/env.json
---
